/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SecondRouteImport } from './routes/second'
import { Route as OrderRouteImport } from './routes/order'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as IndexRouteImport } from './routes/index'

const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondRoute = SecondRouteImport.update({
  id: '/second',
  path: '/second',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/customers': typeof CustomersRoute
  '/kitchen': typeof KitchenRoute
  '/manage': typeof ManageRoute
  '/order': typeof OrderRoute
  '/second': typeof SecondRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/customers': typeof CustomersRoute
  '/kitchen': typeof KitchenRoute
  '/manage': typeof ManageRoute
  '/order': typeof OrderRoute
  '/second': typeof SecondRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/customers': typeof CustomersRoute
  '/kitchen': typeof KitchenRoute
  '/manage': typeof ManageRoute
  '/order': typeof OrderRoute
  '/second': typeof SecondRoute
  '/tables': typeof TablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/customers'
    | '/kitchen'
    | '/manage'
    | '/order'
    | '/second'
    | '/tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/customers'
    | '/kitchen'
    | '/manage'
    | '/order'
    | '/second'
    | '/tables'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/customers'
    | '/kitchen'
    | '/manage'
    | '/order'
    | '/second'
    | '/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  CustomersRoute: typeof CustomersRoute
  KitchenRoute: typeof KitchenRoute
  ManageRoute: typeof ManageRoute
  OrderRoute: typeof OrderRoute
  SecondRoute: typeof SecondRoute
  TablesRoute: typeof TablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second': {
      id: '/second'
      path: '/second'
      fullPath: '/second'
      preLoaderRoute: typeof SecondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  CustomersRoute: CustomersRoute,
  KitchenRoute: KitchenRoute,
  ManageRoute: ManageRoute,
  OrderRoute: OrderRoute,
  SecondRoute: SecondRoute,
  TablesRoute: TablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
